export const INITIALIZE_AVAILABLE_PRODUCTS_STATE = 'INITIALIZE_AVAILABLE_PRODUCTS_STATE';
export const REHYDRATE = 'REHYDRATE';
export const REMOVE_NO_LAND_BASE_PACKAGES = 'REMOVE_NO_LAND_BASE_PACKAGES';
export const REMOVE_NO_LAND_UPGRADES = 'REMOVE_NO_LAND_UPGRADES';
export const RETURN_NO_LAND_PRODUCTS = 'RETURN_NO_LAND_PRODUCTS';